// ============================================================================
// SAFE MEDIA STORAGE CONTRACT
// ============================================================================
// Media bytes live on disk under a configured root (MEDIA_ROOT); PostgreSQL
// stores metadata only (safe relative key, MIME, byte size, SHA-256).
//
// Invariants:
// - storage keys are GENERATED (event id + version + content hash), never
//   caller-supplied paths;
// - absolute names, "..", backslashes and NUL are rejected before any I/O;
// - every resolved path is containment-checked against the root;
// - read verifies the expected checksum; mismatch/missing are explicit errors;
// - delete uses only generated keys and is idempotent.
//
// Write ordering contract (enforced by the caller in src/meal-events.ts):
// stage/write/verify bytes FIRST, then commit the DB transaction; on DB
// failure the caller cleans up staged bytes via delete().

import { mkdir } from "node:fs/promises";
import { resolve, sep } from "node:path";

export class UnsafeStorageKeyError extends Error {
    constructor(key: string) {
        super(`unsafe media storage key rejected: ${JSON.stringify(key)}`);
        this.name = "UnsafeStorageKeyError";
    }
}

export class MediaNotFoundError extends Error {
    constructor(key: string) {
        super(`media not found for key: ${key}`);
        this.name = "MediaNotFoundError";
    }
}

export class MediaChecksumError extends Error {
    constructor(key: string) {
        super(`media checksum mismatch for key: ${key}`);
        this.name = "MediaChecksumError";
    }
}

export interface StoredMediaMetadata {
    storage_key: string;
    mime_type: string;
    byte_size: number;
    sha256: string;
}

export interface MediaStore {
    put(args: {
        event_id: string;
        version: number;
        kind: "photo" | "audio";
        bytes: Uint8Array;
        mime_type: string;
    }): Promise<StoredMediaMetadata>;
    read(storageKey: string, expectedSha256: string): Promise<Uint8Array>;
    delete(storageKey: string): Promise<void>;
}

// Defense-in-depth: keys are always generated by this module, but every entry
// point revalidates before touching the filesystem.
function assertSafeKey(key: string): void {
    if (
        key.length === 0 ||
        key.startsWith("/") ||
        key.includes("\\") ||
        key.includes("\u0000") ||
        key.split("/").includes("..")
    ) {
        throw new UnsafeStorageKeyError(key);
    }
}

export function generateStorageKey(args: {
    event_id: string;
    version: number;
    kind: "photo" | "audio";
    sha256: string;
}): string {
    return `${args.event_id}/${args.version}/${args.kind}-${args.sha256}`;
}

export function isGeneratedStorageKey(args: {
    storage_key: string;
    event_id: string;
    version: number;
    kind: "photo" | "audio";
    sha256: string;
}): boolean {
    return args.storage_key === generateStorageKey(args);
}

function sha256Hex(bytes: Uint8Array): string {
    return new Bun.CryptoHasher("sha256").update(bytes).digest("hex");
}

export function createMediaStore(root: string): MediaStore {
    const resolvedRoot = resolve(root);

    function resolveUnderRoot(key: string): string {
        assertSafeKey(key);
        const path = resolve(resolvedRoot, key);
        if (path !== resolvedRoot && !path.startsWith(resolvedRoot + sep)) {
            throw new UnsafeStorageKeyError(key);
        }
        return path;
    }

    return {
        async put({ event_id, version, kind, bytes, mime_type }) {
            const sha256 = sha256Hex(bytes);
            const storageKey = generateStorageKey({
                event_id,
                version,
                kind,
                sha256,
            });
            const path = resolveUnderRoot(storageKey);
            const dir = path.slice(0, path.lastIndexOf(sep));
            await mkdir(dir, { recursive: true });
            await Bun.write(path, bytes);
            // Verify what actually landed on disk before returning metadata.
            const written = new Uint8Array(await Bun.file(path).arrayBuffer());
            if (sha256Hex(written) !== sha256) {
                throw new MediaChecksumError(storageKey);
            }
            return {
                storage_key: storageKey,
                mime_type,
                byte_size: bytes.byteLength,
                sha256,
            };
        },

        async read(storageKey, expectedSha256) {
            const path = resolveUnderRoot(storageKey);
            const file = Bun.file(path);
            if (!(await file.exists())) {
                throw new MediaNotFoundError(storageKey);
            }
            const bytes = new Uint8Array(await file.arrayBuffer());
            if (sha256Hex(bytes) !== expectedSha256) {
                throw new MediaChecksumError(storageKey);
            }
            return bytes;
        },

        async delete(storageKey) {
            const path = resolveUnderRoot(storageKey);
            const file = Bun.file(path);
            if (await file.exists()) {
                await file.delete();
            }
        },
    };
}
